{
 "title": "Validator Ops Radar | Errors & Warnings",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sig_error" },
   { "name": "sig_warn" },
   { "name": "validator", "query": ".*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img width=\"200px\" src=\"https://www.5elementsnodes.com/wp-content/uploads/2025/07/Gen_White.webp\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors",
   "type": "piechart",
   "description": "Click a slice to filter by validator",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (validator_name) (\n  count_over_time(\n    {job=\"genlayer-node\"}\n    | regexp \"(?s)(?P<payload>\\\\{.*\\\\})\"\n    | line_format \"{{.payload}}\"\n    != \"docker.sock\"\n    | json\n    | (message!=\"HTTP request\")\n    | level=\"error\"\n  [$__range])\n)",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Recurring errors",
   "type": "bargauge",
   "description": "Click an error to view matching log lines",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort_desc(\n  topk(5,\n    sum by (sig) (\n      count_over_time(\n        {job=\"genlayer-node\", validator_name=~\"$validator\"}\n        | regexp \"(?s)(?P<payload>\\\\{.*\\\\})\"\n        | line_format \"{{.payload}}\"\n        |~ \"\\\"level\\\"\\\\s*:\\\\s*\\\"error\\\"\"\n        != \"docker.sock\"\n        | json\n        | (message!=\"HTTP request\")\n        | regexp \"\\\"(?:error|message)\\\"\\\\s*:\\\\s*\\\"(?P<t1>.*?)(?:\\\\\\\\n(?P<t2>.*?))?\\\"\"\n        | label_format sig=\"{{if .t2}}{{.t1}} {{.t2}}{{else}}{{.t1}}{{end}}\"\n        | sig=~\".+\"\n      [$__range])\n    )\n  )\n)",
     "legendFormat": "{{sig}}"
    }
   ]
  },
  {
   "title": "Errors log",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"genlayer-node\", validator_name=~\"$validator\"}\n| regexp \"(?s)(?P<payload>\\\\{.*\\\\})\"\n| line_format \"{{.payload}}\"\n!= \"docker.sock\"\n| json\n| (message!=\"HTTP request\")\n| level=\"error\"\n| regexp \"\\\"(?:error|message)\\\"\\\\s*:\\\\s*\\\"(?P<t1>.*?)(?:\\\\\\\\n(?P<t2>.*?))?\\\"\"\n| label_format sig=\"{{if .t2}}{{.t1}} {{.t2}}{{else}}{{.t1}}{{end}}\"\n| sig=~\"$sig_error\"",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "piechart",
   "description": "Click a slice to filter by validator",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (validator_name) (\n  count_over_time(\n    {job=\"genlayer-node\"}\n    | regexp \"(?s)(?P<payload>\\\\{.*\\\\})\"\n    | line_format \"{{.payload}}\"\n    | json\n    | (level=\"warn\" or level=\"warning\")\n  [$__range])\n)\n",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Recurring warnings",
   "type": "bargauge",
   "description": "Click a warning to view matching log lines",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort_desc(\n  topk(5,\n    sum by (sig) (\n      count_over_time(\n        {job=\"genlayer-node\", validator_name=~\"$validator\"}\n        | regexp \"(?s)(?P<payload>\\\\{.*\\\\})\"\n        | line_format \"{{.payload}}\"\n        | json\n        | (level=\"warn\" or level=\"warning\")\n        | label_format sig=\"{{.message}}\"\n      [$__range])\n    )\n  )\n)",
     "legendFormat": "{{sig}}"
    }
   ]
  },
  {
   "title": "Warnings log",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"genlayer-node\", validator_name=~\"$validator\"}\n| regexp \"(?s)(?P<payload>\\\\{.*\\\\})\"\n| line_format \"{{.payload}}\"\n| json\n| (level=\"warn\" or level=\"warning\")\n|= \"$sig_warn\"",
     "maxLines": 5000
    }
   ]
  }
 ]
}