{
 "title": "WOS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "latest_version", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img width=\"200px\" src=\"https://www.5elementsnodes.com/wp-content/uploads/2025/07/Gen_White.webp\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Validators node version",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "max by(node, validator_name, version, commit, genvm_version) (\n  genlayer_node_info{job=\"prometheus.scrape.genlayer_node\", validator_name!=\"genlayerlabs-full-1\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(node, validator_name) (\n  genlayer_node_info{job=\"prometheus.scrape.genlayer_node\", validator_name!=\"genlayerlabs-full-1\", version=\"$latest_version\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "parser": "jq-backend",
     "root_selector": ".validators\n| map(\n  select(.moniker != null and .moniker != \"\")\n  | {\n      validator_name: .moniker,\n      moniker: .moniker,\n      validator: .validator,\n      status: .status\n    }\n)\n",
     "source": "url",
     "type": "json",
     "url": "https://asimov.5elementsnodes.com/genlayer/validators.json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "expr": "max by(validator_name) (genlayer_node_info{job=\"prometheus.scrape.genlayer_node\"})",
     "legendFormat": "__auto"
    },
    {
     "direction": "backward",
     "expr": "sum by (validator_name) (count_over_time({job=\"genlayer-node\"}[1h]))\n"
    }
   ]
  },
  {
   "title": "Validators not sending logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (validator_name) (count_over_time({job=\"genlayer-node\"}[1h]))\n"
    },
    {
     "parser": "jq-backend",
     "root_selector": ".validators\n| map(\n  select(.moniker != null and .moniker != \"\")\n  | {\n      validator_name: .moniker,\n      moniker: .moniker,\n      validator: .validator,\n      status: .status\n    }\n)\n",
     "source": "url",
     "type": "json",
     "url": "https://asimov.5elementsnodes.com/genlayer/validators.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}