{
 "title": "General Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Genvm executions ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "genlayer_node_genvm_executions", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Leader Proposed total ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "genlayer_node_transactions_leader_proposed_total",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Blocks behind",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "genlayer_node_blocks_behind", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "genlayer_node_uptime_seconds{component=\"node\"}",
     "legendFormat": "{{validator_name}}"
    }
   ]
  }
 ]
}